//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariant
    {
        public int ProductVariantID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<double> ProductCost { get; set; }
        public Nullable<int> ColourId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<int> ProductQty { get; set; }
        public string SKU { get; set; }
    
        public virtual COLOUR COLOUR { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SIZE SIZE { get; set; }
    }
}
