//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.ProductVariants = new HashSet<ProductVariant>();
        }
    
        public int PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
        public Nullable<double> PRODUCT_COST { get; set; }
        public Nullable<double> PRODUCT_PRICE { get; set; }
        public Nullable<int> PRODUCT_TypeID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> PRODUCT_ORDER_NUMBER { get; set; }
        public Nullable<System.DateTime> PRODUCT_CREATE_DATE { get; set; }
        public string PRODUCT_CODE { get; set; }
        public Nullable<int> PRODUCT_QTY { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariant> ProductVariants { get; set; }
    }
}
